### ISSUE TITLE
Tied times get different points

### ISSUE THREAD

**Issue by michael-77** [brownben/munro#11]
Ben,

Poor Robin has been robbed of a point from the Calton Hill FWTN [because of a tie](https://munro-leagues.herokuapp.com/events/FightwiththeNight19-20CaltonHill(BigWeekend)2020-01-24/results) . 

Same times should probably generate the same points score although it's rare enough an occurrence that this may be the first time it's occurred. 

I'm afraid I'm a bit on the busy side to look to diagnose and submit a PR but thought you'd "appreciate" the issue log and can probably fix it quicker anyway! 

Michael (ELO)

**Comment by brownben** [comment]
This is an error due to my manual filtering of results before upload, assigning him the wrong position as I didn't realize their was a tie. The points system used for Fight with the Night just bases the points  off of the position, so unfortunately he got the wrong points. I have now fixed his result.

The system should work in the case of a tie, see Sprintelope 2018 event 2 [Myself and Claire]:
https://munro-leagues.herokuapp.com/leagues/Sprintelope%202018/results/Long 

Thanks for pointing this out,
Ben
